iconomical={module:function(j){var d=window;j.split(".").forEach(function(c){c in d||(d[c]={});d=d[c]})}};var Debugger=function(){};Debugger.log=function(j){try{console.log(j)}catch(d){}};trace=Debugger.log;iconomical.module("iconomical.odi_p2p");
iconomical.odi_p2p.data=function(){function j(a){return h[a]}function d(m,e){var c={};a.forEach(function(a){var f=a[m],b=c[f];b||(b=c[a[m]]={id:f,name:e(f),total:0});b.total+=a[n]});var h=[],f;for(f in c)h.push(c[f]);return h}function c(a,c,e){var h={};p.forEach(function(f){var b=f[a];h[b]||(h[f[a]]={id:b,name:c(b),total:f[e]})});var f=[],t;for(t in h)f.push(h[t]);return f}var e,l,g={},h={},a=[],k=[],p=[],r=[],s=[],n="Total loan amount";return{loadData:function(m){queue().defer(d3.csv,"p2p_regionflow_11jun13.csv").defer(d3.csv,
"p2p_areas2regions.csv").defer(d3.csv,"p2p_areaflow_11jun13.csv").defer(d3.csv,"p2p_all_statistics.csv").defer(d3.csv,"p2p_uk_statistics.csv").defer(d3.csv,"p2p_agg_areas.csv").await(function(c,d,q,f,t,x,b){e=d;l=q;a=f;p=t;r=x;s=b;p2p_region_data=e.filter(function(b){return"NA"!=b["Region lender"]&&"NA"!=b["Region borrower"]});p2p_region_data.forEach(function(b){b.value=parseInt(b["Total loan amount"]);b.poppieLs=parseInt(b["Number lenders"]);b.poppieBs=parseInt(b["Number borrowers"])});e.sort(function(b,
a){return d3.descending(b["Region borrower"],a["Region borrower"])});l.forEach(function(b){g[b["Postcode area"]]=b.Region;h[b["Postcode area"]]=b["Postcode area name"]});a.forEach(function(b){b["Area borrower"]=$.trim(b["Area borrower"]);b["Area lender"]=$.trim(b["Area lender"]);b["Region borrower"]=$.trim(b["Region borrower"]);b["Region lender"]=$.trim(b["Region lender"]);b[n]=Number(b[n])});aggBorrow=d3.nest().key(function(b){return b["Area borrower"]}).rollup(function(b){return d3.sum(b,function(b){return+b["Total loan amount"]})}).entries(a);
aggLend=d3.nest().key(function(b){return b["Area lender"]}).rollup(function(b){return d3.sum(b,function(b){return+b["Total loan amount"]})}).entries(a);var u={};aggBorrow.forEach(function(b){u[b.key]={id:b.key,area:b.key,borrow:b.values,region:g[b.key]}});aggLend.forEach(function(b){u[b.key].lend=b.values});for(var I in u)k.push(u[I]);m()})},getRegionFlowData:function(){return e},getRawRegionData:function(){return l},getAreaFlows:function(){return k},getallStats:function(){return p},getukStats:function(){return r},
getaggAreas:function(){return s},getUniqueRegions:function(){return _.uniq(_.pluck(l,"Region"))},getSimpleLoanSums:function(){return d3.nest().key(function(a){return a["Region lender"]}).rollup(function(a){return d3.sum(a,function(a){return a.value})}).map(e)},getSimpleBorrowSums:function(){return d3.nest().key(function(a){return a["Region borrower"]}).rollup(function(a){return d3.sum(a,function(a){return a.value})}).map(e)},getSimpleLoanSumsasEntries:function(){return d3.nest().key(function(a){return a["Region lender"]}).rollup(function(a){return[{transaction:"lending",
label:"lent",someSum:d3.sum(a,function(a){return a.value})}]}).entries(e)},getSimpleBorrowSumsasEntries:function(){return d3.nest().key(function(a){return a["Region borrower"]}).rollup(function(a){return[{transaction:"borrowing",label:"received",someSum:d3.sum(a,function(a){return a.value})}]}).entries(e)},getPostcodeLendingTotals:function(){return d("Area lender",j)},getPostcodeBorrowingTotals:function(){return d("Area borrower",j)},getRegionLendingTotals:function(){return d("Region lender",function(a){return $.trim(a)})},
getRegionBorrowingTotals:function(){return d("Region borrower",function(a){return $.trim(a)})},getPostcodeRegion:function(a){return g[a]},getPostcodeAreaName:j,getRegionLenders:function(){return c("region",function(a){return $.trim(a)},"lenders")},getRegionBorrowers:function(){return c("region",function(a){return $.trim(a)},"borrowers")},getRegionMeanLend:function(){return c("region",function(a){return $.trim(a)},"avg.loan")},getRegionMeanBorr:function(){return c("region",function(a){return $.trim(a)},
"avg.borr")}}};iconomical.module("iconomical.charts");
iconomical.charts.utils=function(j){function d(c,d){var g=[],h=d3.map();c.forEach(function(a){a=d(a);h.has(a)||(g.push(a),h.set(a,1))});return g}var c=j?j:{};c.makeOrdinalScale=function(c,l){var g=d(c,l);return d3.scale.ordinal().domain(g)};c.makeLinearScale=function(c,d){var g=d3.extent(c,d);g[0]=Math.min(0,g[0]);return d3.scale.linear().domain(g).nice()};c.stackValues=function(c,l){return d(c,l)};c.stackData=function(e,d,g,h){var a=c.stackValues(e,d).map(function(a){return e.filter(function(c){return d(c)==a})});
d3.layout.stack().x(g).y(h)(a)};return c};iconomical.module("iconomical.charts");
iconomical.charts.svg=function(j){var d=arguments.length?j:{},c,e,l,g,h;d.makeSVG=function(a,d,p){a=d3.select(a);var j=a[0][0],s=$(j).width(),n=$(j).height();e=g=s*p;l=h=n*p;p=(s-g)/2;var m=(n-h)/2;return c=a.append(j instanceof SVGElement?"g":"svg").attr("id",d).attr("width",s).attr("height",n).append("g").attr("width",g).attr("height",h).attr("transform","translate("+p+","+m+")")};d.svg=function(a){return arguments.length?(c=val,d):c};d.width=function(a){return arguments.length?(g=a,d):g};d.height=
function(a){return arguments.length?(h=a,d):h};d.chartAreaWidth=function(a){return arguments.length?(e=a,d):e};d.chartAreaHeight=function(a){return arguments.length?(l=a,d):l};$.extend(d,iconomical.charts.utils(d));return d};iconomical.module("iconomical.charts");
iconomical.charts.map=function(j,d){function c(b){function f(b){b=q(c[h(b)]);if(!b)return"";b=b.split(/\s+/);var a=!0;b=d3.select(this).selectAll("tspan").data(b);b.enter().append("tspan");b.attr("dy",function(){var b=a?"0.0em":"1.0em";a=!1;return b}).attr("x",0).text(Object);b.exit().remove()}var c={};b.forEach(function(b){c[a(b)]=b});g.value(function(b){return r(p(c[h(b)]))});var d,j;s?(b=g(e,e.objects[k].geometries).features,d=g.path,j=g.path.centroid):(b=g.features(e,e.objects[k].geometries),
d=d3.geo.path().projection(l),j=d.centroid);d=t.selectAll("path").data(b,function(b){return h(b)}).each(function(b){var a=c[h(b)];b.datum=a}).transition().duration(n).attr("d",d);m&&z&&d.style("fill",function(b){return m(z(c[h(b)]))}).style("stroke",function(b){return d3.rgb(m(z(c[h(b)]))).darker()});q&&(b=x.selectAll("text").data(b,function(b){return h(b)}),b.enter().append("text").attr("text-anchor","middle").attr("transform",function(b){b=g.path.centroid(b);return"translate("+b[0]+","+b[1]+")"}),
b.each(f).transition().duration(n).attr("transform",function(b){b=j(b);return"translate("+b[0]+","+b[1]+")"}))}var e,l,g,h,a,k,p,r,s,n,m,z,A,q=function(b){return h(b)},f=$({});c.events=f;c.mapData=function(b){e=b;var a=topojson.feature(e,e.objects[k]).features.map(function(b){return d3.geo.bounds(b)});b=a.map(function(b){return b[0][0]});var f=a.map(function(b){return b[0][1]}),t=a.map(function(b){return b[1][0]}),a=a.map(function(b){return b[1][1]}),f=[[d3.min(b),d3.min(f)],[d3.max(t),d3.max(a)]];
b=d3.geo.mercator();b.scale(1);var a=b([f[0][0],f[0][1]]),d=b([f[1][0],f[1][1]]),t=c.width()/Math.abs(d[0]-a[0]),a=c.height()/Math.abs(a[1]-d[1]),t=Math.min(a,t);b.scale(t);b.translate([0,0]);f=b([f[0][0],f[1][1]]);b.translate([-f[0],-f[1]]);l=b;g=d3.cartogram().projection(l).value(function(){return 1});c.reset()};c.reset=function(){var b=g.features(e,e.objects[k].geometries),a=d3.geo.path().projection(l),b=t.selectAll("path").data(b,function(b){return h(b)}).enter().append("path").attr("class","map-segment").attr("title",
function(b){return h(b)+": "+b});b.attr("d",a)};c.segments=function(){return"#"+d+" .map-segment"};c.mapName=function(b){return arguments.length?(h=d3.functor(b),c):h};c.dataName=function(b){return arguments.length?(a=d3.functor(b),c):a};c.topoKey=function(b){return arguments.length?(k=b,c):k};c.value=function(b){return arguments.length?(p=d3.functor(b),c):p};c.valueScale=function(b){return arguments.length?(r=d3.functor(b),c):r};c.colourValue=function(b){return arguments.length?(z=d3.functor(b),
c):z};c.morphDuration=function(b){return arguments.length?(n=b,c):n};c.colourScale=function(b){return arguments.length?(m=d3.functor(b),c):m};c.mapLabel=function(b){return arguments.length?(q=d3.functor(b),c):q};c.total=function(b){return arguments.length?(A=b,c):A};c.morph=function(b){return arguments.length?(s=b,c):s};$.extend(c,iconomical.charts.svg(c));var f=c.makeSVG(j,d,0.9),t=f.append("g").attr("class","map"),x=f.append("g").attr("class","labels");return c};iconomical.module("iconomical.odi_p2p");
iconomical.odi_p2p.gor=function(){function j(){var c=d.getRegionLendingTotals();trace(c);var g=d3.extent(c,function(a){return a.total});trace(g);g[0]=0;var h=d3.scale.linear().domain(g).range([1,100]),g=d3.scale.linear().domain(g).range(["white","#558800"]);e.morph(!0).colourScale(g).valueScale(h);e(c)}var d,c,e;return{initialise:function(l,g){d3.select("#LoanSum").on("click.from_gor",function(){var c=d.getRegionLendingTotals();trace(c);var a=d3.extent(c,function(a){return a.total});trace(a);a[0]=
0;var k=d3.scale.linear().domain(a).range([1,100]),a=d3.scale.linear().domain(a).range(["white","#558800"]);e.morph(!0).colourScale(a).valueScale(k);e(c)});d3.select("#BorrSum").on("click.from_gor",function(){var c=d.getRegionBorrowingTotals();trace(c);var a=d3.extent(c,function(a){return a.total});trace(a);a[0]=0;var k=d3.scale.linear().domain(a).range([1,100]),a=d3.scale.linear().domain(a).range(["white","#990099"]);e.morph(!0).colourScale(a).valueScale(k);e(c)});d3.select("#LoanPops").on("click.from_gor",
function(){var c=d.getRegionLenders();trace(c);var a=d3.extent(c,function(a){return a.total});trace(a);a[0]=0;var k=d3.scale.linear().domain(a).range([1,100]),a=d3.scale.linear().domain(a).range(["white","#558800"]);e.morph(!0).colourScale(a).valueScale(k);e(c)});d3.select("#BorrPops").on("click.from_gor",function(){var c=d.getRegionBorrowers();trace(c);var a=d3.extent(c,function(a){return a.total});trace(a);a[0]=0;var k=d3.scale.linear().domain(a).range([1,100]),a=d3.scale.linear().domain(a).range(["white",
"#990099"]);e.morph(!0).colourScale(a).valueScale(k);e(c)});d3.select("#AvrgLoan").on("click.from_gor",function(){var c=d.getRegionMeanLend();trace(c);var a=d3.extent(c,function(a){return a.total});trace(a);a[0]=0;var k=d3.scale.linear().domain(a).range([1,100]),a=d3.scale.linear().domain(a).range(["white","#558800"]);e.morph(!0).colourScale(a).valueScale(k);e(c)});d3.select("#AvrgBorr").on("click.from_gor",function(){var c=d.getRegionMeanBorr();trace(c);var a=d3.extent(c,function(a){return a.total});
trace(a);a[0]=0;var k=d3.scale.linear().domain(a).range([1,100]),a=d3.scale.linear().domain(a).range(["white","#990099"]);e.morph(!0).colourScale(a).valueScale(k);e(c)});d3.select("#levelIIheader").on("click.from_gor",function(){j()});d=l;d3.json("gor_reduced.json",function(d,a){c=a;a.objects.gor_conv.geometries.forEach(function(a){a.id=a.properties.id=a.properties.NAME});e=iconomical.charts.map("#map","mapChart");e.value(function(a){return a.total}).colourValue(function(a){return a.total}).mapName(function(a){return a.id}).dataName(function(a){return a.id}).mapLabel(function(a){return a.id}).morphDuration(1E3).topoKey("gor_conv");
e.mapData(c);g()})},mapChart:function(){return e},showNormal:j}};iconomical.module("iconomical.odi_p2p");
iconomical.odi_p2p.barchart=function(){function j(a){d3.selectAll(".rankerblocks").sort(function(c,d){return d3.descending(c[a],d[a])}).transition().duration(1500).attr("transform",function(a,c){return"translate("+l(c)+",0)"})}var d=function(){};d3.format(",");var c=d3.format(".3s"),e=d3.select("#rAnkchArt").append("svg").attr("id","rankingSVG").attr("width",620).attr("height",140).append("g"),l=d3.scale.ordinal().rangeBands([0,590],0.1),g=e.append("g").attr("class","rankYaxis").attr("transform",
"translate(606,0)"),h=d3.scale.linear().range([50,0]),a=d3.svg.axis().orient("left").ticks(5).tickPadding(-10).tickFormat(c),k=e.append("g").attr("class","rankYaxis").attr("transform","translate(606,0)"),p=d3.scale.linear().range([50,110]),r=d3.svg.axis().orient("left").ticks(5).tickSubdivide(4).tickPadding(-10).tickFormat(c),s={setupRankingAxes:function(c,d,e,j,q,f){f&&l.domain(d3.range(c.length));h.domain([0,d3.max(c,function(a){return a[d]})+q]);a.scale(h);g.transition().duration(500).call(a);
p.domain([0,d3.max(c,function(a){return a[d]})+q]);r.scale(p);k.transition().duration(500).call(r);d3.selectAll(".tick").filter(function(){return 0==this.__data__}).transition().delay().duration(250).style("opacity",1E-6);d3.select("#rAnkcAptOp").html(e);d3.select("#rAnkcApbOt").html(j)},goMakeThoseRankingBars:function(a,c,g,j,k,f){e.selectAll(".rankerblocks").remove();a=e.selectAll(".rankerblocks").data(a.sort(function(a,c){return d3.descending(a[f],c[f])})).enter().append("g").attr("class","rankerblocks").attr("transform",
function(a,c){return"translate("+l(c)+",0)"});a.append("rect").attr("class","Lbar").attr("x",function(){return l.rangeBand()/2}).attr("width",function(){return l.rangeBand()-1}).attr("y",function(a){return h(a[c])}).attr("height",function(a){return 50-h(a[c])}).on("mouseenter",function(a){d(a)}).append("title").attr("class","Btxt").text(function(a){return a.area+" ("+a.region+") "+j+": "+a[c]});a.append("rect").attr("class","Bbar").attr("x",function(){return l.rangeBand()/2}).attr("width",function(){return l.rangeBand()-
1}).attr("y",function(){return p(0)}).attr("height",function(a){return p(a[g])-50}).on("mouseenter",function(a){d(a)}).append("title").attr("class","Btxt").text(function(a){return a.area+" ("+a.region+") "+k+": "+a[g]});a.append("text").attr("class","Alabel").attr("y",130).attr("text-anchor","middle").attr("text-align","center").text(function(a){return a.area})},sortRankers:j,remakeRankingBars:function(a,c,d,g,k,f){a=e.selectAll(".rankerblocks").data(a,function(a){return a.id});a.select(".Lbar").transition().duration(1E3).attr("y",
function(a){return h(a[c])}).attr("height",function(a){return 50-h(a[c])}).select("title").attr("class","Ltxt").text(function(a){return a.area+" ("+a.region+") "+g+": "+a[c]});a.select(".Bbar").transition().duration(1E3).attr("y",function(){return p(0)}).attr("height",function(a){return p(a[d])-50}).select("title").attr("class","Ltxt").text(function(a){return a.area+" ("+a.region+") "+k+": "+a[d]});a.select(".Alabel").text(function(a){return a.area});j(f)},afterMapOver:function(a){var c=a.id,d;void 0!=
c&&(2>=c.length?d="id":d="region",d3.selectAll(".Alabel, .Bbar, .Lbar").transition().duration().each("end",function(){d3.select(this).classed("sElEctEd",!1)}),d3.selectAll(".Alabel").filter(function(a){return a[d]==c}),d3.selectAll(".Alabel, .Bbar, .Lbar").filter(function(a){return a[d]==c}).transition().duration().each("end",function(){d3.select(this).classed("sElEctEd",!0)}))},afterMapOut:function(){d3.selectAll(".Alabel, .Bbar, .Lbar").transition().duration().each("end",function(){d3.select(this).classed("sElEctEd",
!1)})},highlightRegion:function(a){d3.selectAll(".Bbar, .Lbar").filter(function(c){return c.region==a}).classed("sElEctEd",!0)},highlightPostcode:function(a){d3.selectAll(".Bbar, .Lbar").filter(function(c){return c.id==a}).classed("sElEctEd",!0);d3.selectAll(".Alabel").filter(function(c){return c.id==a}).classed("sElEctEd",!0).style("font-size","8pt")},unhighlight:function(){d3.selectAll(".Alabel, .Bbar, .Lbar").classed("sElEctEd",!1)},mouseEnterCallback:function(a){return a?(d=a,s):d}};return s};iconomical.module("iconomical.odi_p2p");
iconomical.odi_p2p.stacks=function(){function j(){d3.selectAll(".tick").filter(function(){return 0==this.__data__}).transition().delay().duration(250).style("opacity",1E-6)}function d(){}var c=function(){},e=function(){},l=function(){},g=function(){},h=function(){};d3.format(",");var a=d3.format(".3s"),k=d3.select("#stAckchArt").append("svg").attr("id","stackSVG").attr("width",346).attr("height",480).append("g").attr("transform","translate(2,12)"),p=d3.scale.ordinal().domain(["lending","borrowing"]).rangeBands([0,
296,0.15]),r=d3.scale.ordinal().domain(["borrowing","lending"]).range(["#990099","#558800"]),s=k.append("g").attr("class","stackYaxis").attr("transform","translate(119,0)"),n=d3.svg.axis().orient("left").ticks(8).tickPadding(-20).tickFormat(a),m=d3.scale.linear().range([430,0]),z=d3.scale.linear().range([0.1,1]),A=d3.scale.linear().range([0.1,1]),q={showStackData:function(a,e,x){a.sort(function(a,b){return d3.ascending(a,b)});e.sort(function(a,b){return d3.ascending(a.key,b.key)});x.sort(function(a,
b){return d3.ascending(a.key,b.key)});stufftoStack=[];for(i=0;i<a.length;i++)stufftoStack.push({key:a[i],values:[e[i].values[0],x[i].values[0]]});a=d3.layout.stack().values(function(a){return a.values}).x(function(a){return a.transaction}).y(function(a){return a.someSum})(stufftoStack);var b=d3.extent(e,function(a){return a.values[0].someSum}),u=d3.extent(x,function(a){return a.values[0].someSum});e=d3.sum(e,function(a){return a.values[0].someSum});x=d3.sum(x,function(a){return a.values[0].someSum});
z.domain(b);A.domain(u);m.domain([0,d3.max([e,x])]);n.scale(m);s.call(n);j();a.forEach(function(a){a.id=a.key;a.values.forEach(function(b){b.key=b.id=a.key})});k.selectAll(".stackSegment").remove();k.selectAll(".statsbar").remove();k.selectAll(".stackSegment").data(a).enter().append("g").attr("class","stackSegment").selectAll(".stackrect").data(function(a){return a.values}).enter().append("rect").attr("class","stackrect").attr("x",function(a){return p(a.transaction)}).attr("width",100).attr("y",function(a){return m(a.y0+
a.y)}).attr("height",function(a){return m(a.y0)-m(a.y0+a.y)}).style("fill-opacity",function(a){return"borrowing"==a.transaction?A(a.y):z(a.y)}).style("fill",function(a){return r(a.transaction)}).style("stroke",function(a){return d3.rgb(r(a.transaction)).darker()}).on("click",function(a,b){h(a,b,this)}).on("mouseover",function(a,b){l(a,b,this)}).on("mouseenter",function(a,b){c(a,b)}).on("mouseout",function(a,b){g(a,b,this)}).on("mouseleave",d).append("title").text(function(a){return this.parentNode.parentNode.__data__.key+
", total "+a.label+": "+a.someSum})},sortStacks:function(a,c,d){var b=[];"up"==d?b=a.sort(function(a,b){return d3.ascending(a.values[c].someSum,b.values[c].someSum)}):b=a.sort(function(a,b){return d3.descending(a.values[c].someSum,b.values[c].someSum)});a=b;d=d3.layout.stack().values(function(a){return a.values}).x(function(a){return a.transaction}).y(function(a){return a.someSum});myReStacker=d3.selectAll(".stackSegment").data(d(a));myReStacker.selectAll(".stackrect").data(function(a){return a.values}).transition().duration(2E3).attr("y",
function(a){return m(a.y0+a.y)}).attr("height",function(a){return m(a.y0)-m(a.y0+a.y)}).style("fill-opacity",function(a){return"lending"==a.transaction?z(a.y):A(a.y)}).style("fill",function(a){return r(a.transaction)}).style("stroke",function(a){return d3.rgb(r(a.transaction)).darker()}).select("title").text(function(a){return this.parentNode.parentNode.__data__.key+", total "+a.label+": "+a.someSum})},showStatistics:function(a){k.selectAll(".stackSegment").transition().duration(250).attr("stroke-opacity",
1E-6).attr("fill-opacity",1E-6).remove();var c=d3.max([a[0]["avg.loan"],a[0]["avg.borr"]]),d=d3.scale.linear().domain([0,c+c/10]).range([430,0]);n.scale(d);s.transition().duration(250).call(n);j();a=k.selectAll(".statsbar").data(a).enter().append("g").attr("class","statsbar");a.append("rect").attr("class","loanmEAnbar").attr("x",0).attr("width",100).attr("y",function(a){return d(a["avg.loan"])}).attr("height",function(a){return 430-d(a["avg.loan"])}).append("title").text(function(a){return"average loan: "+
a["avg.loan"]});a.append("line").attr("class","loanmEdiAnline").attr("x1",-20).attr("x2",100).attr("y1",function(a){return d(a["median.loan"])}).attr("y2",function(a){return d(a["median.loan"])});a.append("rect").attr("class","borrmEAnbar").attr("x",148).attr("width",100).attr("y",function(a){return d(a["avg.borr"])}).attr("height",function(a){return 430-d(a["avg.borr"])}).append("title").text(function(a){return"average receivings: "+a["avg.borr"]});a.append("line").attr("class","borrmEdiAnline").attr("x1",
148).attr("x2",248).attr("y1",function(a){return d(a["median.borr"])}).attr("y2",function(a){return d(a["median.borr"])})},afterMapOver:function(a,c){d3.select(c).style("stroke","black").style("stroke-width","1px");var d=a.id;d3.selectAll(".stackSegment").filter(function(a){return a.key==d}).selectAll(".stackrect").style("stroke","black").style("stroke-width","1.5px").classed("selectedStack",!0)},afterMapOut:function(a,c){d3.select(c);d3.selectAll(".selectedStack").style("stroke",function(a){return d3.rgb(r(a.transaction)).darker()}).style("stroke-width",
"1px").classed("selectedStack",!1)},highlight:function(a){d3.selectAll(".stackSegment").selectAll(".stackrect").filter(function(c){return c.key==a}).style("stroke","black").style("stroke-width","2px").classed("selectedStack",!0)},unhighlight:function(){d3.selectAll(".selectedStack").style("stroke",function(a){return d3.rgb(r(a.transaction)).darker()}).style("stroke-width","1px").classed("selectedStack",!1)},svg:function(){return k},mouseEnterCallback:function(a){return a?(c=a,q):c},mouseLeaveCallback:function(a){return a?
(e=a,q):e},mouseOverCallback:function(a){return a?(l=a,q):l},mouseOutCallback:function(a){return a?(g=a,q):g},mouseClickCallback:function(a){return a?(h=a,q):h}};return q};iconomical.module("iconomical.odi_p2p");
iconomical.odi_p2p.p2p=function(){function j(){function e(){return"stat"==y}function j(a){a.forEach(function(a){"lenders borrowers population total.loan total.borr min.loan min.borr max.loan max.borr avg.loan avg.borr median.loan median.borr sd.loan sd.borr borr.parts loan.parts".split(" ").forEach(function(b){a[b]=parseInt(a[b])});a["prop.lend"]=d3.round(a.lenders/(a.population/1E4));a["prop.borr"]=d3.round(a.borrowers/(a.population/1E4))})}function g(){3==f&&B.svg().selectAll(".statsbar").transition().duration(250).attr("stroke-opacity",
1E-6).attr("fill-opacity",1E-6).remove();f=b;y="money";w=!1;t="none";v.setupRankingAxes(H,"lend","lending totals","receiving totals",5E6,!0);v.goMakeThoseRankingBars(H,"lend","borrow","lent","received","lend");B.showStackData(J,K,L);v.sortRankers("lend");B.sortStacks(stufftoStack,0,"up");d3.selectAll(".selectedLabel").classed("selectedLabel",!1);d3.select("#LoanSum").classed("selectedLabel",!0);y="money";w=!0;t="UK";A(E,b);setTimeout(h,2E3)}function h(){d3.selectAll("#barWrapper, #stackWrapper, #DaHeader").style("display",
"inline").transition().duration(1E3).style("opacity",1);c.showNormal()}function a(a,b,c,d,e,f){var g=[],h=[],g=d3.nest().key(function(a){return a.id}).rollup(function(a){return[{transaction:"lending",label:e,someSum:d3.sum(a,function(a){return a[c]})}]}).entries(a),h=d3.nest().key(function(a){return a.id}).rollup(function(a){return[{transaction:"borrowing",label:f,someSum:d3.sum(a,function(a){return a[d]})}]}).entries(a);B.showStackData(b,g,h)}function k(a){if(f!=G){var d,e;f==b?(e=D.filter(function(b){return b.id==
a.id}),d=u,d3.selectAll(c.mapChart().segments()).filter(function(b){return b.id==a.id}).style("stroke","black").style("stroke-width","1px"),v.highlightRegion(a.id)):f==u&&(e=C.filter(function(b){return b.id==a.id}),d=G,v.highlightPostcode(a.id));A(e,d);B.highlight(a.id)}}function p(){s();B.unhighlight();d3.selectAll(c.mapChart().segments()).style("stroke","darkgrey").style("stroke-width","0.5px");v.unhighlight()}function r(){"money"==y?(v.setupRankingAxes(H,"lend","lending totals","borrowing totals",
5E6,!0),v.remakeRankingBars(H,"lend","borrow","lent",w?"borrowed":"received",w?"lend":"borrow")):"people"==y?(v.setupRankingAxes(C,"lenders","number of lenders","number of recipients",500,!0),v.remakeRankingBars(C,"lenders","borrowers","lenders","recipients",w?"lenders":"borrowers")):e()&&(v.setupRankingAxes(C,"avg.loan","average lent","average received",8E3,!0),v.remakeRankingBars(C,"avg.loan","avg.borr","average","median",w?"avg.loan":"avg.borr"));f!=b&&v.sortRankers("region")}function s(){if(f==
b)A(E,b);else if(f==u){var a=D.filter(function(a){return a.region==x});A(a,u)}}function n(){r();if("money"==y)if(f==b)B.showStackData(J,K,L);else{var c=H.filter(function(a){return a.region==x}),d=c.map(function(a){return a.id});a(c,d,"lend","borrow","lent","received")}else"people"==y?f==b?a(D,J,"lenders","borrowers","lenders","recipients"):f==u&&(c=C.filter(function(a){return a.region==x}),d=gatheredAllAreas.map(function(a){return a.id}),a(c,d,"lenders","borrowers","lenders","recipients")):e();B.sortStacks(stufftoStack,
w?0:1,"up");s()}function m(a){B.showStatistics(a);y="stat";A(a,G)}function z(){}function A(a,c){c==b?(d3.select("#levelIheader").html("UK").classed("heading",!0).classed("selectedHeader",!0).classed("hasPointer",!1),d3.select("#levelIIheader").classed("heading",!1).classed("selectedHeader",!1).html(""),d3.select("#levelIIIheader").classed("heading",!1).classed("selectedHeader",!1).html(""),d3.select("#levelIVheader").classed("heading",!1).classed("selectedHeader",!1).html("")):c==u?(d3.select("#levelIheader").html("UK").classed("heading",
!0).classed("selectedHeader",!1).classed("hasPointer",!0).on("click",g),d3.select("#levelIIheader").html(a[0].region).classed("heading",!0).classed("selectedHeader",!0),d3.select("#levelIIIheader").classed("heading",!1).classed("selectedHeader",!1).html(""),d3.select("#levelIVheader").classed("heading",!1).classed("selectedHeader",!1).html("")):c==I?(d3.select("#levelIheader").html("UK").classed("heading",!0).classed("selectedHeader",!1),d3.select("#levelIIheader").html(a[0].region).classed("heading",
!0).classed("selectedHeader",!1),d3.select("#levelIIIheader").html(a[0].id).classed("heading",!0).classed("selectedHeader",!0),d3.select("#levelIVheader").classed("heading",!1).classed("selectedHeader",!1).html("")):c==G&&("UK"==a[0].region?(d3.select("#levelIheader").html(a[0].region).classed("heading",!0).classed("selectedHeader",!0).classed("hasPointer",!0).on("click",z),d3.select("#levelIIheader").html(" stats").classed("heading",!0).classed("selectedHeader",!1).on("click.from_p2p",null)):(d3.select("#levelIheader").html("UK").classed("heading",
!0).classed("selectedHeader",!1).classed("hasPointer",!0).on("click",z),d3.select("#levelIIheader").html(a[0].region).classed("heading",!0).classed("selectedHeader",!1).classed("hasPointer",!0).on("click",z),d3.select("#levelIIIheader").html(a[0].id).classed("heading",!0).classed("selectedHeader",!0).classed("hasPointer",!1),d3.select("#levelIVheader").html("stats").classed("heading",!0).classed("selectedHeader",!1).classed("hasPointer",!1)));d3.selectAll("#LoanPeeps svg, #BorrPeeps svg").remove();
d3.select("#LoanSum").html("&#163;"+M(a[0]["total.loan"]));d3.select("#BorrSum").html("&#163;"+M(a[0]["total.borr"]));d3.select("#LoanPops .amount").html(F(a[0].lenders));d3.select("#BorrPops .amount").html(F(a[0].borrowers));d3.select("#LoanPeeps").append("svg").selectAll(".users").data(d3.range(a[0]["prop.lend"])).enter().append("use").attr("class","users lenders").attr("x",function(a,b){return 7>b?16*b:14>b?16*b-112:21>b?16*b-224:28>b?16*b-336:0}).attr("y",function(a,b){return 7>b?0:14>b?32:21>
b?64:28>b?96:108}).attr("xlink:href",function(){return 0.5>=Math.random()?"#girl":"#boy"});d3.select("#LoanPeepsTitles .amount").html(d3.round(a[0]["prop.lend"]));d3.select("#BorrPeeps").append("svg").selectAll(".users").data(d3.range(a[0]["prop.borr"])).enter().append("use").attr("class","users borrowers").attr("x",function(a,b){return 7>b?16*b:14>b?16*b-112:21>b?16*b-224:28>b?16*b-336:0}).attr("y",function(a,b){return 7>b?0:14>b?32:21>b?64:28>b?96:108}).attr("xlink:href",function(){return 0.5>Math.random()?
"#girl":"#boy"});d3.select("#BorrPeepsTitles .amount").html(d3.round(a[0]["prop.borr"]));d3.select("#AvrgLoan .amount").html("&#163;"+F(d3.round(a[0]["avg.loan"])));d3.select("#AvrgBorr .amount").html("&#163;"+F(d3.round(a[0]["avg.borr"])));d3.select("#MedianLoan .amount").html("&#163;"+F(d3.round(a[0]["median.loan"])));d3.select("#MedianBorr .amount").html("&#163;"+F(d3.round(a[0]["median.borr"])))}function q(a){d3.selectAll(".selectedColumn").classed("selectedColumn",!1);d3.selectAll(".selectedLabel").classed("selectedLabel",
!1);d3.select(a).classed("selectedLabel",!0);d3.select(a.parentNode).classed("selectedColumn",!0)}var f,t,x=null,b=0,u=1,I=2,G=3,y="money",w=!1,J=d.getUniqueRegions(),H=d.getAreaFlows(),C=d.getaggAreas(),D=d.getallStats(),E=d.getukStats(),K=d.getSimpleLoanSumsasEntries(),L=d.getSimpleBorrowSumsasEntries();d3.scale.ordinal().domain(["borrowing","lending"]).range(["#990099","#558800"]);j(E);j(D);j(C);trace("UK");trace(E);trace("Region");trace(D);trace("AggArea");trace(C);var F=d3.format(","),M=d3.format(".3s"),
v=iconomical.odi_p2p.barchart();v.mouseEnterCallback(function(){});var B=iconomical.odi_p2p.stacks();B.mouseOverCallback(function(a){k(a)}).mouseOutCallback(function(a){p(a)}).mouseClickCallback(function(a){a=a.id;f==b?(x=a,f=u):f==u&&(f=G);n();trace("drill state now "+f)});d3.selectAll(c.mapChart().segments()).on("click",function(a){x=a.id;f=u;n()}).on("mouseover",function(a){k(a)}).on("mouseout",function(){p()});g();d3.select("#LoanSum").on("click.from_p2p",function(){y="money";w=!0;n();q(this)});
d3.select("#BorrSum").on("click.from_p2p",function(){y="money";w=!1;n();q(this)});d3.select("#LoanPops").on("click.from_p2p",function(){y="people";w=!0;n();q(this)});d3.select("#BorrPops").on("click.from_p2p",function(){y="people";w=!1;n();q(this)});d3.select("#AvrgLoan").on("click.from_p2p",function(){if(!e()||!w)e()&&!w&&(B.sortStacks(stufftoStack,0,"up"),v.sortRankers("avg.loan")),e()||(f==b&&(m(E),v.sortRankers("avg.loan")),f==u&&m(D.filter(function(a){return a.region==t}))),y="stat",w=!0,r(),
q(this)});d3.select("#AvrgBorr").on("click.from_p2p",function(){if(!e()||w)e()&&w&&(B.sortStacks(stufftoStack,1,"up"),v.sortRankers("avg.borr")),e()||(f==b&&(m(E),v.sortRankers("avg.borr")),f==u&&m(D.filter(function(a){return a.region==t}))),y="stat",w=!1,r(),q(this)})}var d=iconomical.odi_p2p.data(),c=iconomical.odi_p2p.gor();return{initialise:function(){d.loadData(function(){c.initialise(d,function(){j()})})},plotData:j}};
